"""Initial migration

Revision ID: c647c5e99a0f
Revises: 
Create Date: 2026-04-22 06:59:10.403455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c647c5e99a0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('weekly', 'monthly'), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('positif', sa.Integer(), nullable=True),
    sa.Column('negatif', sa.Integer(), nullable=True),
    sa.Column('netral', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'period_key', name='uq_period')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'analyst'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_tag', sa.String(length=20), nullable=False),
    sa.Column('algorithm', sa.Enum('nb', 'svm', 'lr', 'rf'), nullable=False),
    sa.Column('feature_method', sa.Enum('tfidf', 'bow', 'w2v'), nullable=False),
    sa.Column('ngram_min', sa.SmallInteger(), nullable=True),
    sa.Column('ngram_max', sa.SmallInteger(), nullable=True),
    sa.Column('train_split', sa.SmallInteger(), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('precision_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recall_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('f1_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.Column('fp', sa.Integer(), nullable=True),
    sa.Column('fn', sa.Integer(), nullable=True),
    sa.Column('tn', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('model_file_path', sa.String(length=255), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('trained_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trained_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_app_id', sa.String(length=100), nullable=False),
    sa.Column('max_reviews', sa.Integer(), nullable=True),
    sa.Column('filter_bintang', sa.String(length=20), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SELESAI', 'GAGAL'), nullable=True),
    sa.Column('reviews_scraped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('predicted_label', sa.Enum('POSITIF', 'NEGATIF', 'NETRAL'), nullable=True),
    sa.Column('conf_positif', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('conf_negatif', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('conf_netral', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocessing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraping_job_id', sa.Integer(), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.Enum('cleaning', 'case_folding', 'tokenisasi', 'normalisasi', 'stopword', 'stemming', 'done'), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SELESAI', 'GAGAL'), nullable=True),
    sa.Column('pos_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('neg_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('neu_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraping_job_id'], ['scraping_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraping_job_id', sa.Integer(), nullable=True),
    sa.Column('user_id_hash', sa.String(length=32), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('sentiment_label', sa.Enum('POSITIF', 'NEGATIF', 'NETRAL'), nullable=True),
    sa.Column('sentiment_conf', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraping_job_id'], ['scraping_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('idx_app_version', ['app_version'], unique=False)
        batch_op.create_index('idx_review_date', ['review_date'], unique=False)
        batch_op.create_index('idx_sentiment', ['sentiment_label'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('idx_sentiment')
        batch_op.drop_index('idx_review_date')
        batch_op.drop_index('idx_app_version')

    op.drop_table('reviews')
    op.drop_table('preprocessing_jobs')
    op.drop_table('prediction_logs')
    op.drop_table('scraping_jobs')
    op.drop_table('model_versions')
    op.drop_table('users')
    op.drop_table('sentiment_trends')
    # ### end Alembic commands ###
